services:

    reverseproxy:
        image: reverse-proxy
        ports:
            - 8080:8080
        restart: always

    app:
        depends_on:
            - reverseproxy
        image: app-sumar
        restart: always
